# Generated by Django 4.2.5 on 2023-09-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default='2002-02-02', help_text='Vous devez avoir plus de 15 ans.', verbose_name='Date de naissance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=True, help_text="Votre email sera masquée aux autres utilisateurs si vous choisissez 'NON'.", verbose_name='Peux être contacté'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='can_data_be_shared',
            field=models.BooleanField(choices=[(True, 'Oui'), (False, 'Non')], default=True, help_text="Votre profil sera masqué aux autres utilisateurs et vos informations non partagées si vous choisissez 'NON'.", verbose_name='Partager ses données'),
            preserve_default=False,
        ),
    ]
