# Generated by Django 4.2.5 on 2023-09-29 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_remove_issue_issue_type_issue_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug_name',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('iOS', 'iOS'), ('Android', 'Android')], default='', max_length=128, verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributions', through='project.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Précise si le projet doit être considéré comme actif. Décochez ceci plutôt que de supprimer le projet.', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Nom du projet'),
            preserve_default=False,
        ),
    ]
