# Generated by Django 4.2.5 on 2023-09-30 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_project_slug_name_alter_project_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug_name',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature'), ('Task', 'Task')], default='', max_length=32, verbose_name='Balise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='Nom'),
            preserve_default=False,
        ),
    ]
