# Generated by Django 4.2.5 on 2023-09-30 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_alter_issue_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, help_text='Description facultative', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(help_text='Donnez un nom à votre issue', max_length=256, verbose_name="Nom de l'issue"),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description facultative', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Donnez un nom à votre projet', max_length=256, verbose_name='Nom du projet'),
        ),
    ]
