# Generated by Django 4.2.5 on 2023-09-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_issue_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
